name: CI/CD for Node.js REST-API
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents:write
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4
    
      - name: Login DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME -- password-stdin

    
      - name: Build Docker image
